create table tipo_contato (
    id              integer generated by default as identity,
    descricao		varchar(50) not null,
    primary key (id)
);

create table agenda (
    id             integer generated by default as identity,
    nome           varchar(100) not null,
    id_tipo        integer not null,
    contato        varchar(100) not null,
    primary key (id),
	foreign key (id_tipo) references tipo_contato (id)
);

INSERT INTO tipo_contato (descricao)
VALUES ('Telefone fixo');

INSERT INTO tipo_contato (descricao)
VALUES ('Telefone celular');

INSERT INTO tipo_contato (descricao)
VALUES ('Telefone recado');

INSERT INTO tipo_contato (descricao)
VALUES ('e-mail');

INSERT INTO tipo_contato (descricao)
VALUES ('website');


INSERT INTO agenda (nome, id_tipo, contato)
VALUES ('Alexandre Magno', 2, '85.9.9999.9999');

